name: Gradle Build

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java-version: [ 21 ]
        distribution: [ adopt ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Save Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '*/build/reports'

      - name: Build jlink Image with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: jlinkZip

      - name: Save Image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.os }}-${{ matrix.java-version }}-${{ matrix.distribution }}
          path: '*/build/image.zip'
